// IM app ID
const SDKAPPID = process.env.INIT_APP_TIM_SDK_ID
const TEST_USERID = 'test000'


export const UI_PLATFORMS = {
  APP: 'app',
  WEB: 'web'
}

// im侧边栏宽度
export const IM_CHAT_SIDEBAR_WIDTH = {
  reader: 320, // 观看端
  admin: 320, // 管理端
  pusher: '100%' // 推流端
}

const SPECIAL_MESSAGE = 'BSYIM_SPECIAL_MESSAGE'
const CALLBACK_MESSAGE = 'BSYIM_CALLBACK_MESSAGE'
const IMCALLBACK_MESSAGE = 'BSYIM_IMCALLBACK_MESSAGE'
const IM_CALLBACK_ASK_BEHAVIOR = 'IM_CALLBACK_ASK_BEHAVIOR'
const IM_CALLBACK_TAB_BEHAVIOR = 'IM_CALLBACK_TAB_BEHAVIOR'

const BSYIM_IMLOGIN = 'BSYIM_IMLOGIN'
const BSYIM_IMREDAY = 'BSYIM_IMREDAY'
const BSYIM_IMERROR = 'BSYIM_IMERROR'
const BSYIM_IMONMESSAGE = 'BSYIM_IMONMESSAGE'
const BSYIM_GROUP_FORBIDDENLIST = 'BSYIM_GROUP_FORBIDDENLIST'
const BSYIM_GROUP_GETGROUPMEMBERLIST = 'BSYIM_GROUP_GETGROUPMEMBERLIST'
const BSYIM_IM_INLINE_NUM = 'BSYIM_IM_INLINE_NUM'
const BSYIM_IM_LIKE_NUM = 'BSYIM_IM_LIKE_NUM'
const BSYIM_IM_LIVE_STATUS = 'BSYIM_IM_LIVE_STATUS'
const BSYIM_KICKED_OUT = 'BSYIM_KICKED_OUT'
const BSYIM_TAB_CHANGE = 'BSYIM_TAB_CHANGE'
const BSYIM_TAB_CHAT = '_CHAT'
const BSYIM_TAB_ACTIVITY = '_ACTIVITY'
const BSYIM_TAB_CLASSES = '_CLASSES'
const BSYIM_TAB_ASK = '_ASK'
const BSYIM_TAB_GROUP_ACTIVITY = '_GROUP_ACTIVITY'
const BSYIM_TAB_LIVEGOODS = '_LIVEGOODS'
const BSYIM_TAB_GOODS = '_STUDENT_GOODS'
const BSYIM_TAB_WAITING = '_WAITING'

const IM_CHANGE_TABKEY = 'BSYIM_IM_CHANGE_TABKEY'
const BSYIM_EMOJI_DISPLAY_CHANGE = 'BSYIM_EMOJI_DISPLAY_CHANGE'
const BSYIM_MASK_CLICK = 'BSYIM_MASK_CLICK'

const BSYIM_PUSH_ADDR_CHANGED = 'BSYIM_LIVE_PUSH_CHANGED'
const BSYIM_PULL_ADDR_CHANGED = 'BSYIM_LIVE_PULL_CHANGED'
const BSYIM_SWITCH_ONLINENUM = 'BSYIM_SWITCH_ONLINENUM'
const BSYIM_GROUP_URL_SENDER = 'BSYIM_GROUP_URL_SENDER'
const BSYIM_GROUP_SHELF_SHOW = 'BSYIM_GROUP_SHELF_SHOW'
const BSYIM_GROUP_SHELF_HIDE = 'BSYIM_GROUP_SHELF_HIDE'
const BSYIM_GROUP_COMMON_CONTROL = 'BSYIM_GROUP_COMMON_CONTROL'

const BSYIM_MULTI_PULL_ADDR_CHANGED = 'BSYIM_MULTI_PULL_ADDR_CHANGED'
const BSYIM_MULTI_PUSH_ADDR_CHANGED = 'BSYIM_MULTI_PUSH_ADDR_CHANGED'

const MULTI_PULL_ADDR_CHANGED = 'MULTI_PULL_ADDRESS_CHANGED'
const MULTI_PUSH_ADDR_CHANGED = 'MULTI_PUSH_ADDRESS_CHANGED'
const LIVE_PUSH_ADDR_CHANGED = 'PUSH_ADDRESS_CHANGED'
const LIVE_PULL_ADDR_CHANGED = 'PULL_ADDRESS_CHANGED'
const GROUP_LIKE_NUM = 'GROUP_LIKE_NUM'
const GROUP_SILENCE = 'GROUP_SILENCE'
const GROUP_URL_SENDER = 'GROUP_URL_SENDER'
const GROUP_SHELF_SHOW = 'GROUP_SHELF_SHOW'
const GROUP_SHELF_HIDE = 'GROUP_SHELF_HIDE'
const GROUP_COMMON_CONTROL = 'GROUP_COMMON_CONTROL'
const CUSTOM_MSG = 'CUSTOM_MSG'
const GROUP_EVENT_NOTIFY = 'GROUP_EVENT_NOTIFY'
const IMG_PRELOAD = 'IMG_PRELOAD'
const LIVE_STATUS_CHANGED = 'LIVE_STATUS_CHANGED'

const API_URL = process.env.INIT_APP_API_URL
const STUDENT_API_URL = process.env.INIT_APP_STUDENT_API_URL
const SCHOOL_URL = process.env.INIT_APP_SCHOOL_URL

const BSYIM_EVENT_TYPE = 'BSYIM_EVENT_TYPE'
const BSYIM_IFRAME_LOAD = 'BSYIM_IFRAME_LOAD'
const BSYIM_GET_GROUP_PROFILE = 'BSYIM_GET_GROUP_PROFILE'
const BSYIM_SEND_MESSAGE = 'BSYIM_SEND_MESSAGE'
const BSYIM_SEND_MESSAGE_LIKE = 'BSYIM_SEND_MESSAGE_LIKE'
const BSYIM_GET_GROUP_MEMBERLIST = 'BSYIM_GET_GROUP_MEMBERLIST'
const BSYIM_GET_MESSAGELIST = 'BSYIM_GET_MESSAGELIST'
const ELEMENT_STYLES = 'ELEMENT_STYLES'
export const BSYIM_GET_GROUP_USERPROFILE = 'BSYIM_GET_GROUP_USERPROFILE'
const BSYIM_SEND_CUSTSOM_IMAGE = 'BSYIM_SEND_CUSTSOM_IMAGE'
export const BSYIM_IM_INIT_MESSAGE = 'BSYIM_IM_INIT_MESSAGE'

const BSYIM_SPECIAL_MESSAGE_TYPE = {
  ASK: 'ASK',
  ACTIVITY: 'ACTIVITY'
}

const BSYIM_INITIAL_MODE = {
  tabMode: '_tabMode',
  imMode: '_onlyImMode'
}

const QUESTION_ENUM = new Map([
  [1, '单选题'],
  [2, '多选题'],
  [3, '不定选'],
  [4, '判断题']
])

const STATUS_ENUM = {
  0: '未售卖',
  1: '已上架',
  2: '已停售'
}


const BSYIM_COLLAPSE_SAME_MESSAGE = 'BSYIM_COLLAPSE_SAME_MESSAGE'

// eslint-disable-next-line import/prefer-default-export
export {
  SDKAPPID,
  TEST_USERID,
  SPECIAL_MESSAGE,
  CALLBACK_MESSAGE,
  STUDENT_API_URL,
  SCHOOL_URL,
  IMCALLBACK_MESSAGE,
  GROUP_LIKE_NUM,
  GROUP_SILENCE,
  BSYIM_IMLOGIN,
  BSYIM_IMREDAY,
  BSYIM_IMERROR,
  BSYIM_IMONMESSAGE,
  BSYIM_GROUP_FORBIDDENLIST,
  BSYIM_GROUP_GETGROUPMEMBERLIST,
  BSYIM_IM_INLINE_NUM,
  BSYIM_IM_LIVE_STATUS,
  BSYIM_IM_LIKE_NUM,
  LIVE_STATUS_CHANGED,
  BSYIM_KICKED_OUT,
  LIVE_PUSH_ADDR_CHANGED,
  LIVE_PULL_ADDR_CHANGED,
  BSYIM_PUSH_ADDR_CHANGED,
  BSYIM_PULL_ADDR_CHANGED,
  API_URL,
  IM_CALLBACK_ASK_BEHAVIOR,
  IM_CALLBACK_TAB_BEHAVIOR,
  BSYIM_TAB_CHANGE,
  BSYIM_TAB_CHAT,
  BSYIM_TAB_ACTIVITY,
  BSYIM_TAB_CLASSES,
  BSYIM_TAB_ASK,
  BSYIM_TAB_GROUP_ACTIVITY,
  BSYIM_TAB_LIVEGOODS,
  BSYIM_TAB_GOODS,
  BSYIM_TAB_WAITING,
  CUSTOM_MSG,
  IMG_PRELOAD,
  GROUP_EVENT_NOTIFY,
  BSYIM_SWITCH_ONLINENUM,
  GROUP_URL_SENDER,
  GROUP_SHELF_SHOW,
  GROUP_SHELF_HIDE,
  BSYIM_GROUP_URL_SENDER,
  BSYIM_GROUP_SHELF_SHOW,
  BSYIM_GROUP_SHELF_HIDE,
  GROUP_COMMON_CONTROL,
  BSYIM_GROUP_COMMON_CONTROL,
  BSYIM_EVENT_TYPE,
  IM_CHANGE_TABKEY,
  MULTI_PULL_ADDR_CHANGED,
  MULTI_PUSH_ADDR_CHANGED,
  BSYIM_MULTI_PULL_ADDR_CHANGED,
  BSYIM_MULTI_PUSH_ADDR_CHANGED,
  BSYIM_EMOJI_DISPLAY_CHANGE,
  BSYIM_IFRAME_LOAD,
  BSYIM_GET_GROUP_PROFILE,
  BSYIM_SEND_MESSAGE,
  BSYIM_SEND_MESSAGE_LIKE,
  BSYIM_GET_GROUP_MEMBERLIST,
  BSYIM_GET_MESSAGELIST,
  BSYIM_SEND_CUSTSOM_IMAGE,
  BSYIM_MASK_CLICK,
  BSYIM_COLLAPSE_SAME_MESSAGE,
  ELEMENT_STYLES,
  BSYIM_SPECIAL_MESSAGE_TYPE,
  BSYIM_INITIAL_MODE,
  QUESTION_ENUM,
  STATUS_ENUM
}
